services:
  web:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped

  dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    # No restart policy for dev convenience

volumes:
  node_modules:
