services:
  - type: static
    name: tj-personal-site
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /assets/*
        name: Cache-Control
        value: public,max-age=31536000,immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache
